### ISSUE TITLE
Add a restart button

### ISSUE THREAD

**Issue by JustA3DObject** [gdsc-ipsacademy/Connect-Four-Game#10]
When the game ends, the program waits for 3000 milli seconds and then just quits by itself, which is confusing for the users as they'll think that game just crashed. Or if someone wants a rematch, they have to relaunch the game to do that.

Instead of waiting for 3000 milli seconds before closing, the game should show two buttons giving the options to either "Restart" or "Quit" the game after the play ends.

**Comment by itrajkov** [comment]
Can I pick this up?

**Comment by JustA3DObject** [comment]
> Can I pick this up?

Sure go ahead
