### ISSUE TITLE
Add different levels of AI.

### ISSUE THREAD

**Issue by JustA3DObject** [gdsc-ipsacademy/Connect-Four-Game#12]
Right now the game has only one type of AI to play against which is impossible to beat.

Try to add these levels of AI for the player to select from:

- Easy: AI makes random moves
- Intermediate: AI uses score method but only in two random directions instead of all four.
- Hard: AI uses score method in all four directions.
- Impossible: AI uses minmax algorithm at 6 depth.
- GOD Mode: AI uses minmax algorithm at 7 depth.

**Comment by itrajkov** [comment]
Can I take this?

**Comment by itrajkov** [comment]
@JustA3DObject What exactly did you mean by "score method"?

**Comment by JustA3DObject** [comment]
There's a file named `score_ai.py` which calculates a score for making various connections in the game. 
In horizontal, vertical and both diagonal directions, if the AI connects 2 pieces, it gets 10 points, if it connects 3 pieces, it gets 50 points and if it connects 4 pieces, it gets 100 points. 
Similarly it also checks the human player moves. If the human connects pieces, AI's score is reduced which is why it blockes the human player when they are about to make a connect 4 in the next move.
