### ISSUE TITLE
Add some kind of visual for the user while the AI is thinking.

### ISSUE THREAD

**Issue by JustA3DObject** [gdsc-ipsacademy/Connect-Four-Game#7]
When the AI is thinking it's next move,  there is no visual representation of it in the game window which can confuse the users making them think the game crashed.

A good and most common solution is to add a visual or a graphic on the game window whenever it's AI's turn for the user to know that the program didn't crash, the AI is just thinking.

Alternatively, try to optimise the AI even further so that it takes less calculation time even on depth 7 or makes better decisions on depth 6.

**Comment by SasikaSankalana** [comment]
@JustA3DObject Can you assign me to this?

**Comment by JustA3DObject** [comment]
> @JustA3DObject Can you assign me to this?

Sure I'll get to it in a bit.

**Comment by JustA3DObject** [comment]
Hey @SasikaSankalana I've assigned you this issue.
